name: test-libcint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-custom-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: build libcint.so
        run: |
          cd ~
          git clone https://github.com/sunqm/libcint.git
          cd libcint
          mkdir build; cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=/usr
          make -j4
          sudo make install

      - name: test crate libcint
        run: |
          cd libcint
          cargo test

  test-build-dynamic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test crate libcint
        run: |
          cd libcint
          cargo test --features="build_from_source"

  test-build-static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test crate libcint
        run: |
          cd libcint
          cargo test --features="build_from_source static"

  test-build-static-qcint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test crate libcint
        run: |
          cd libcint
          cargo test --features="build_from_source static qcint"
